<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
    exclude-result-prefixes="s">
  <xsl:output method="html" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <title>MapifyIt | Sitemap</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&amp;display=swap');
          
          :root {
            --bg: #030712;
            --card-bg: rgba(255, 255, 255, 0.03);
            --border: rgba(255, 255, 255, 0.08);
            --accent: #3b82f6;
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
          }

          body {
            font-family: 'Outfit', system-ui, -apple-system, sans-serif;
            background-color: var(--bg);
            color: var(--text-main);
            margin: 0;
            padding: 40px 20px;
            line-height: 1.5;
            -webkit-font-smoothing: antialiased;
          }

          .container {
            max-width: 1000px;
            margin: 0 auto;
          }

          header {
            margin-bottom: 48px;
            text-align: center;
          }

          h1 {
            font-size: 3rem;
            font-weight: 700;
            margin: 0 0 12px 0;
            background: linear-gradient(135deg, #fff 0%, #6366f1 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            letter-spacing: -0.02em;
          }

          p.subtitle {
            color: var(--text-muted);
            font-size: 1.1rem;
          }

          .table-wrapper {
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 20px;
            overflow: hidden;
            backdrop-filter: blur(12px);
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
          }

          table {
            width: 100%;
            border-collapse: collapse;
            text-align: left;
          }

          th {
            background: rgba(255, 255, 255, 0.05);
            color: var(--text-muted);
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.1em;
            padding: 20px 24px;
            border-bottom: 1px solid var(--border);
          }

          td {
            padding: 18px 24px;
            border-bottom: 1px solid var(--border);
            font-size: 0.95rem;
          }

          tr:last-child td {
            border-bottom: none;
          }

          tr:hover td {
            background: rgba(255, 255, 255, 0.02);
            transition: background 0.2s ease;
          }

          .url-link {
            color: var(--accent);
            text-decoration: none;
            font-weight: 500;
            transition: opacity 0.2s;
          }

          .url-link:hover {
            opacity: 0.8;
            text-decoration: underline;
          }

          .priority-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 100px;
            font-size: 0.8rem;
            font-weight: 600;
            background: rgba(59, 130, 246, 0.1);
            color: var(--accent);
            border: 1px solid rgba(59, 130, 246, 0.2);
          }

          .freq-badge {
            color: var(--text-muted);
            font-size: 0.85rem;
          }

          .date-text {
            font-family: monospace;
            font-size: 0.85rem;
            color: var(--text-muted);
          }

          footer {
            margin-top: 40px;
            text-align: center;
            font-size: 0.85rem;
            color: var(--text-muted);
          }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>Index Sitemap</h1>
            <p class="subtitle">Generated by MapifyIt Spatial Intelligence Platform</p>
          </header>

          <div class="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>URL Location</th>
                  <th>Priority</th>
                  <th>Frequency</th>
                  <th>Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="s:urlset/s:url">
                  <tr>
                    <td>
                      <a class="url-link">
                        <xsl:attribute name="href">
                          <xsl:value-of select="s:loc"/>
                        </xsl:attribute>
                        <xsl:value-of select="s:loc"/>
                      </a>
                    </td>
                    <td>
                      <span class="priority-badge">
                        <xsl:value-of select="s:priority"/>
                      </span>
                    </td>
                    <td>
                      <span class="freq-badge">
                        <xsl:value-of select="s:changefreq"/>
                      </span>
                    </td>
                    <td>
                      <span class="date-text">
                        <xsl:value-of select="s:lastmod"/>
                      </span>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>

          <footer>
            Total pages indexed: <xsl:value-of select="count(s:urlset/s:url)"/> | 
            Generated on: <xsl:value-of select="s:urlset/s:url[1]/s:lastmod"/>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
